//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CreditCardEntry.java
//  @ Date : 4/21/2014
//  @ Author : 
//
//




public class CreditCardEntry {
	private String name;
}
